//Catapult 1 - player's catapult
BIS_shooter_1 setposASL getposASL BIS_shooterpos;
BIS_shooter_1 setdir getdir BIS_shooterpos;
BIS_crewAidF_1 setposASL getposASL BIS_crewFpos;
BIS_crewAidF_1 setdir getdir BIS_crewFpos;
BIS_crewAidR_1 setposASL getposASL BIS_crewRpos;
BIS_crewAidR_1 setdir getdir BIS_crewRpos;
BIS_crewAidL_1 setposASL getposASL BIS_crewLpos;
BIS_crewAidL_1 setdir getdir BIS_crewLpos;